name: Selenium TC execution

on:
  schedule:
    - cron: "0 4,16 * * 1-5"

jobs:

  Google-tests:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Execute all unit tests in the solution
    - name: Execute Google tests
      run: dotnet test --filter TestCategory=google

    - name: Upload Report
      uses: actions/upload-artifact@v4.3.1
      with:
        name: googleReport
        path: SeleniumProject/test-output/**
        if-no-files-found: error
        retention-days: 90


  Apex-tests:

    runs-on: windows-latest  # For a list of available runner types, refer to
                                 # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
    # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
    
    # Execute all unit tests in the solution
      - name: Execute Apex tests
        run: dotnet test --filter TestCategory=Apex

      - name: Upload Report
        uses: actions/upload-artifact@v4.3.1
        with:
          name: apexReport
          path: SeleniumProject/test-output/**
          if-no-files-found: error
          retention-days: 90
  
  E2E-tests:

    runs-on: windows-latest  # For a list of available runner types, refer to
                                         # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
            
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
            
    # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
            
    # Execute all unit tests in the solution
      - name: Execute E2E tests
        run: dotnet test
        
      - name: Upload Report
        uses: actions/upload-artifact@v4.3.1
        with:
          name: e2eReport
          path: SeleniumProject/test-output/**
          if-no-files-found: error
          retention-days: 90